---
title: Centro Cultural de Barra Velha
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: O conceito do CCBV surgiu em 2018 com a finalidade de aproximar as artes
  em todas as suas formas das pessoas, sejam elas crianças, adolescentes, jovens,
  adultos ou idosos, oferecendo um espaço para se sentir bem e ganhar novas habilidades.
  Aqui no CCBV você encontra professores experientes e que amam compartilhar as artes
  que sabem.
baseurl: 
url: 
markdown: kramdown
theme: minima
permalink: "/:categories/:title"
plugins:
- jekyll-feed
